### ISSUE TITLE
Shadow for close button in unfocused windows

### ISSUE THREAD

**Issue by Defman21** [crutchcorn/eXGTK#12]
Don't know if this a "by design" feature but I think we should remove that
![screen](http://i.imgur.com/VEnkHOc.png)

**Comment by crutchcorn** [comment]
Is that a shadow on the right?

**Comment by Defman21** [comment]
yep

**Comment by crutchcorn** [comment]
I can remove that I think.

**Comment by Defman21** [comment]
`gtk-widgets.css`, lines 435-588

**Comment by crutchcorn** [comment]
That's it??? Just remove that??? Well then. Okay. :P

**Comment by Defman21** [comment]
Yep, try to remove that. Trying to override these settings in window-control.css doesn't work.

**Comment by crutchcorn** [comment]
It's seemed to have worked

**Comment by Defman21** [comment]
Great! Please commit that :)
