### ISSUE TITLE
Shows 4 buttons inactive windows upon hover

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/eXGTK#13]
![screenshot from 2015-04-20 14 24 38](https://cloud.githubusercontent.com/assets/9100169/7240907/8d123f62-e769-11e4-874c-562064569b0d.png)
This is a no no.

**Comment by Defman21** [comment]
Yep, very ugly. I'm already fixed it.

**Comment by Defman21** [comment]
Just give me some time to fix other stuff and I'll do a pull request.

**Comment by crutchcorn** [comment]
Sweet stuff! Thanks for all the help man!
