### ISSUE TITLE
Clean up the source

### ISSUE THREAD

**Issue by Defman21** [crutchcorn/eXGTK#18]
There's a lot of code that should be structured. The branch: https://github.com/crutchcorn/eXGTK/tree/cleanup
Until the source is dirty I don't see any reasons to continue working on it. This job takes for about 2-7 days.

**Comment by crutchcorn** [comment]
Here here! Glad you agree. We'll take care of this soon enough

**Comment by Defman21** [comment]
Just merged cleanup and master. But here's still a lot of work.

**Comment by Defman21** [comment]
Structure was changed. Fixed.
