### ISSUE TITLE
Scroll-bar is weirdly thin and matches background too much

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/eXGTK#2]
![screenshot from 2015-04-16 14 55 11](https://cloud.githubusercontent.com/assets/9100169/7192242/a4f7547e-e448-11e4-8a70-e4e5cf7ba674.png)
That white part is the scrollbar. Didn't even notice at first

**Comment by Defman21** [comment]
I'll change the width of the scrollbar.

**Comment by Defman21** [comment]
Fixed in https://github.com/crutchcorn/eXGTK/commit/4e6f3d20293accf4daa87a0a964b6c90279d6dcf
