### ISSUE TITLE
Exit dialog 

### ISSUE THREAD

**Issue by varlesh** [crutchcorn/eXGTK#22]
Not active dialg not have transparent and fadded font
![1](https://cloud.githubusercontent.com/assets/8083855/7247628/2151b14e-e814-11e4-9537-24bbaf00fbcc.png)
Active dialog have problem with button
![2](https://cloud.githubusercontent.com/assets/8083855/7247633/2a3a0cb6-e814-11e4-9825-e092e2d84180.png)

**Comment by Defman21** [comment]
Will fix.

**Comment by Defman21** [comment]
Fixed in cleanup branch, will be soon in the master.
