### ISSUE TITLE
Buttons Are Too Compact

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/eXGTK#3]
![screenshot from 2015-04-16 14 56 18](https://cloud.githubusercontent.com/assets/9100169/7192304/1b9cd388-e449-11e4-8fa1-4bdbad187c8e.png)
![screenshot from 2015-04-16 14 56 27](https://cloud.githubusercontent.com/assets/9100169/7192305/1d3d5938-e449-11e4-9e04-52aa44f8004b.png)
The nicer size is like Evopop's theme

**Comment by crutchcorn** [comment]
Working on now

**Comment by crutchcorn** [comment]
The padding is PERFECT, but the sizing of the buttons aren't large enough

**Comment by Defman21** [comment]
Yep, you should change it in SVG's directly.

**Comment by crutchcorn** [comment]
That's it? Well shit. Lol. I didn't see that

**Comment by Defman21** [comment]
Yep, they're 13x12 pixels instead of 16x16 (like in Evopop theme)

**Comment by crutchcorn** [comment]
Will fix now. :)

**Comment by Defman21** [comment]
Metacity buttons still small.

**Comment by Defman21** [comment]
Nevermind, I fixed it.

**Comment by Defman21** [comment]
Fixed in https://github.com/Defman21/eXGTK/commit/0b1086cebf1a5be69958403d969958d980fa01d3
