### ISSUE TITLE
Separators not present or invisible 

### ISSUE THREAD

**Issue by robby14** [crutchcorn/eXGTK#4]
![screenshot from 2015-04-17 12 16 35](https://cloud.githubusercontent.com/assets/11992666/7200470/938fc8a0-e4fd-11e4-994b-a1f4e0349d6c.png)
![screenshot from 2015-04-17 12 15 59](https://cloud.githubusercontent.com/assets/11992666/7200469/938d2d3e-e4fd-11e4-839a-2e08a9979def.png)

The first picture is from standard Elementary OS theme the latter from xgtk, as you can see in the second one, separators in the path directory are not present or invisible, same thing for the tabs too and it's hard to see the "x" to close them too

**Comment by crutchcorn** [comment]
Noticed that myself. I think it's related to the crappy handling of tabs (see images below)
Elementary:
![screenshot from 2015-04-17 03 37 49](https://cloud.githubusercontent.com/assets/9100169/7200610/8db335c4-e4b3-11e4-8195-5f41f21d8083.png)
XGTK:
![Uploading Screenshot from 2015-04-17 03:37:38.png . . .]()

**Comment by robby14** [comment]
yeah, it's likely

**Comment by crutchcorn** [comment]
@Defman21, you now have push access to the repo. At this point I would be willing to give you the repo. I don't deserve it

**Comment by Defman21** [comment]
I hope you'll continue report about bugs :)

**Comment by crutchcorn** [comment]
Should I transfer it?

**Comment by Defman21** [comment]
You don't have to do that.

**Comment by crutchcorn** [comment]
Alright. I may save it for a rainy day and do a load more work on it
