### ISSUE TITLE
Menus not readable

### ISSUE THREAD

**Issue by robby14** [crutchcorn/eXGTK#5]
![screenshot from 2015-04-17 12 24 07](https://cloud.githubusercontent.com/assets/11992666/7200566/93669f4c-e4fe-11e4-9d1f-82e6e5089f6c.png)
![screenshot from 2015-04-17 12 23 12](https://cloud.githubusercontent.com/assets/11992666/7200567/9368fbfc-e4fe-11e4-82e1-ff2f5b0eb6b0.png)

The first picture is from Elementary OS theme the latter from xgtk, in the latter, menus are very ugly and the text is hardly readable. 
In my opinion, copying the elementary theme would be the best thing, since that it's colours are consistent with xgtk ones (and of course with yosemite ones too).
There are also those bad blue highlights...

**Comment by crutchcorn** [comment]
I agree. I will be removing the blue highlights. It's a matter of them not being themed. You will see them in many places. What do you think they should be? Anything comparable in Yosemite?

**Comment by robby14** [comment]
As I said before, the Elementary ones are perfect (light grey) to me, so I would do a copy-paste from elementary menus theme, I think it's pretty nice and consistent

**Comment by crutchcorn** [comment]
Eh fooy. You're no fun ;P

**Comment by robby14** [comment]
that's what I think xD but it's just an idea of mine hahaha

**Comment by crutchcorn** [comment]
:+1:

**Comment by varlesh** [comment]
+1 fix please ))

**Comment by beamju** [comment]
:+1:

**Comment by jihadislammuslimallah** [comment]
:+1: Fix it.

**Comment by crutchcorn** [comment]
Am busy today and most of manana (SO many projects). This will probably be the first issue fixed. They set up the panels in a really weird way so I need to keep playing with that

**Comment by Sidorr** [comment]
Сonfirm. Fix it, please.

**Comment by Defman21** [comment]
:+1:

**Comment by inpr1se** [comment]
Fix it.

**Comment by robby14** [comment]
Could you stop from writing "fix it"? I mean the dev understood, he says yes, that's it. Give him his time. Just confirm the bug if you're interested to see it fixed.

**Comment by crutchcorn** [comment]
Thanks @robby14. I don't mean to be rude, but I would like to clean up this thread. I will be fixing this as I myself really want me some working XGTK. ;P

**Comment by robby14** [comment]
I was defending you because everyone was pressing you to fix It, I just said to give you more time xD

**Comment by robby14** [comment]
Oh sorry,  I didn't get it well what you said 👍

**Comment by Defman21** [comment]
I've fixed that. Works fine to me.

**Comment by robby14** [comment]
Ps.. You can delete these comment of mine to clean up 👍

**Comment by robby14** [comment]
Oh thanks @Defman21 I'll try it out tomorrow

**Comment by crutchcorn** [comment]
Pull #9 does not work for me

**Comment by crutchcorn** [comment]
He got it. I am stupid

**Comment by Defman21** [comment]
Btw root popups (or however it's called, e.g. Ethernet Popup) looks a bit different than child popups (in the same popup Ethernet). Root popups a bit transparent than child popups. I don't know how I can fix that, seems like GtkMenu items draws at least 2 backgrounds - one for themselves, one for children group.

**Comment by crutchcorn** [comment]
I saw that myself. The transparency isn't very high and the background of the child popups isn't too bad so I won't worry about that.

**Comment by crutchcorn** [comment]
BTW, what do you use to inspect GTK3?

**Comment by Defman21** [comment]
gtkinspector. Try to open a popup and press Ctrl+Shift+I

**Comment by Defman21** [comment]
If the hotkey won't work for you - you have to install gtk3 dev tools (look for a package yourself, I don't remember the correct name)

**Comment by crutchcorn** [comment]
Tight. Thanks
libgtk-3-dev

**Comment by robby14** [comment]
Hi, I'm sorry, I'm kinda new in this git world, I have some questions:
1. which is the right xgtk folder (with the fix) that I have to donwload this one of @crutchcorn or that one of @Defman21 ?
2. How do you counsel me to update my xgtk theme? Should I download your xgtk folder and put it in the theme folder (/usr/share/themes/)? Or maybe should I make a git clone of your xgtk in /usr/share/themes/ ?
Thank you

**Comment by crutchcorn** [comment]
@robby14, glad you spoke in an old issue rather than raising a new one. :) Be happy to help. 
1) Both @Defman21 and myself have worked (who are we kidding this is @Defman21's baby now ;D) on this theme. Thusly it is only one theme so it doesn't matter at all. :)
2) Alright, so what you do is `git clone https://github.com/eOS-themes/eXGTK.git` in whatever folder you want, then `sudo mv eXGTK /usr/share/themes/` :)

**Comment by crutchcorn** [comment]
Either that, or you can `cd /usr/share/themes` and then `git clone https://github.com/eOS-themes/eXGTK.git`

**Comment by robby14** [comment]
about the first, I made a mistake (in fact I deleted the first question, but... to late xD) I've seen that it's the same folder.
2. so then I have to do "git pull" form /usr/share /themes/EXGTK_FOLDER right?

**Comment by robby14** [comment]
that's a stupid question, there's no need to answer hahah that's quite obvious.
thank you

**Comment by crutchcorn** [comment]
No worries. After all, didn't you JUST make a git after I announced I forked XGTK? :)
2) You can do `git pull`, but `git pull origin master` would be much nicer to do. :)

**Comment by robby14** [comment]
yes, exactly xD.
oh what's the difference between the two? (if it's something easy and fast to say, otherwise I google it later)

**Comment by crutchcorn** [comment]
The long short of it is that just doing `git pull` will pull down sources of whatever branch you're on (we have many branches of code that we merge when they are ready for everyone else to use). By doing `git pull origin master`, you're pulling the branch we want you guys to pull purposefully (because you're saying "pull this branch specificly") and can help with something going wrong. Idealy, you can do git pull, but; to each, their own.

**Comment by robby14** [comment]
Perfect. Thanks again
